Improve init code for the ghosts.
dgomes/iia-ia-pacman pull request #3
Opened 2018-10-30 13:49 UTC by mariolpantunes

Added code to improve the random wait of the ghosts.
Also removed the debugging messages.

2018-10-30 16:25 UTC, dgomes commented on game.py
> +        self._ghosts = [Ghost(self.map, wait[g]) for g in range(0,self._n_ghosts)]
Não gosto de lógica dos fantasmas no Game... :(

2018-10-30 16:26 UTC, dgomes commented on game.py
> +        self._ghosts = [Ghost(self.map, wait[g]) for g in range(0,self._n_ghosts)]
Porque não ter os ghosts a detectar que ha outro ghost na vicinity e só sair qd o mesmo já estiver longe. Mesma lógico pode ser usada para eles não se encavalitarem...

2018-10-30 17:38 UTC, mariolpantunes commented
Fiz a tua sugestão.
Os fantasmas têm um parametro de visibilidade e tentam afastar-se uns dos outros.

2018-10-30 20:56 UTC, dgomes requested changes

2018-10-30 20:56 UTC, dgomes commented on game.py
> +    def __init__(self, mapfile, n_ghosts=GHOSTS, lives=LIVES, timeout=TIMEOUT, max_wait_ghost=MAX_AWAIT_GHOST):
remove option

2018-10-30 20:56 UTC, dgomes commented on game.py
> +        self.max_wait_ghost = max_wait_ghost
it's not even used....

2018-10-30 20:56 UTC, dgomes commented on game.py
> +MAX_AWAIT_GHOST = 20
remove

2018-11-02 12:05 UTC, mariolpantunes commented
Consegues fazer merge agora?

2018-11-02 12:08 UTC, dgomes commented on ghost.py
> +    def __init__(self, mapa, wait=10, buff_size=9, visibility_radius=3):
depois da nossa discussão, melhor tirar wait, buff_size e colocar difficulty_level

2018-11-14 12:37 UTC, dgomes commented
Ha conflitos e o PR tem commits a ficheiros sem modificações. Deves fazer um rebase.

2018-11-19 17:31 UTC, closed without merging